$LastCommit = (git log -p -1 --date=iso)
$Sha = $LastCommit[0].Substring(7,8)
$commitNumber = (git rev-list --all --count)
$DateUpdate = $LastCommit[2].Substring(8,25)
$VersionFile = [System.IO.File]::ReadAllLines("..\PuzzelLibrary\Version.cs")
$VersionFile[6] = $VersionFile[6].Remove(41,3).Insert(41,$commitNumber)
$VersionFile[7] = $VersionFile[7].Remove(44,8).Insert(44,$Sha)
$VersionFile[8] = $VersionFile[8].Remove(80,25).Insert(80,$DateUpdate)
[System.IO.File]::WriteAllLines("..\PuzzelLibrary\Version.cs",$VersionFile)